// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {format} from '../models';

export function CountMonograms(arg1:string):Promise<{[key: string]: number}>;

export function DecodeCaesarCipher(arg1:string,arg2:number):Promise<string>;

export function Format(arg1:string,arg2:format.FormatOptions):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MonogramIndexOfCoincidence(arg1:string):Promise<number>;
