// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {format} from '../models';

export function ColumnarTransposition(arg1:string,arg2:number,arg3:Array<number>):Promise<string>;

export function CountMonograms(arg1:string):Promise<{[key: string]: number}>;

export function DecodeCaesarCipher(arg1:string,arg2:number):Promise<string>;

export function DecodePolybiusCipher(arg1:string,arg2:string):Promise<string>;

export function DecodeSubsitutionCipher(arg1:string,arg2:{[key: number]: number}):Promise<string>;

export function Format(arg1:string,arg2:format.FormatOptions):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InferSpaces(arg1:string):Promise<string>;

export function MonogramIndexOfCoincidence(arg1:string):Promise<number>;
