// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ColumnarTransposition(arg1, arg2, arg3) {
  return window['go']['main']['App']['ColumnarTransposition'](arg1, arg2, arg3);
}

export function CountMonograms(arg1) {
  return window['go']['main']['App']['CountMonograms'](arg1);
}

export function DecodeCaesarCipher(arg1, arg2) {
  return window['go']['main']['App']['DecodeCaesarCipher'](arg1, arg2);
}

export function DecodePolybiusCipher(arg1, arg2) {
  return window['go']['main']['App']['DecodePolybiusCipher'](arg1, arg2);
}

export function DecodeSubsitutionCipher(arg1, arg2) {
  return window['go']['main']['App']['DecodeSubsitutionCipher'](arg1, arg2);
}

export function Format(arg1, arg2) {
  return window['go']['main']['App']['Format'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InferSpaces(arg1) {
  return window['go']['main']['App']['InferSpaces'](arg1);
}

export function MonogramIndexOfCoincidence(arg1) {
  return window['go']['main']['App']['MonogramIndexOfCoincidence'](arg1);
}
