// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountMonograms(arg1) {
  return window['go']['main']['App']['CountMonograms'](arg1);
}

export function DecodeCaesarCipher(arg1, arg2) {
  return window['go']['main']['App']['DecodeCaesarCipher'](arg1, arg2);
}

export function Format(arg1, arg2) {
  return window['go']['main']['App']['Format'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MonogramIndexOfCoincidence(arg1) {
  return window['go']['main']['App']['MonogramIndexOfCoincidence'](arg1);
}
